-- 1. DATABASE TABLE (Project Logs)
create table if not exists public.project_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  subsystem_id text not null check (subsystem_id in ('mechanical', 'electrical', 'software', 'logistics')),
  title text not null,
  content text not null,
  author text not null,
  date date not null default current_date,
  images jsonb
);

-- 2. ENABLE ROW LEVEL SECURITY
alter table public.project_logs enable row level security;

-- 3. POLICIES (Security Rules)
-- Allow EVERYONE to READ logs
create policy "Public Read Access"
  on public.project_logs
  for select
  to anon, authenticated
  using (true);

-- Allow ONLY LOGGED IN users to INSERT/UPDATE/DELETE
create policy "Authenticated Write Access"
  on public.project_logs
  for all
  to authenticated
  using (true)
  with check (true);

-- 4. STORAGE (Image Bucket)
-- Note: You might need to create the 'log-images' bucket manually in the dashboard if this script fails on strict permission setups,
-- but usually this SQL works in the editor.
insert into storage.buckets (id, name, public)
values ('log-images', 'log-images', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Public Access to Images"
  on storage.objects for select
  using ( bucket_id = 'log-images' );

create policy "Authenticated Upload Images"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'log-images' );

create policy "Authenticated Update/Delete Images"
  on storage.objects for update
  to authenticated
  using ( bucket_id = 'log-images' );

create policy "Authenticated Delete Images"
  on storage.objects for delete
  to authenticated
  using ( bucket_id = 'log-images' );
